[project]
name = "docx-link-renderer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
    "python-docx>=1.1.2",
    "requests>=2.32.4",
]
