# Name of the GitHub Actions workflow.
name: Build Cross-Platform Executables

# Controls when the workflow will run.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    # We now define the full build matrix here, including architecture.
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
            name: WordImageTool_Windows
          - os: macos-14 # Use macos-14 for the ARM64 (Apple Silicon) build
            arch: arm64
            name: WordImageTool_macOS_arm64
          - os: macos-12 # Use macos-12 for the x86_64 (Intel) build
            arch: x86_64
            name: WordImageTool_macOS_x86_64

    # Run each job on the specified OS.
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies with uv
      run: |
        uv sync
        uv pip install pyinstaller
      shell: bash

    # Step 5: Run PyInstaller to build the executable.
    # No longer needs the universal2 flag. It will build for the runner's native architecture.
    - name: Build with PyInstaller
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          uv run pyinstaller --noconfirm --onefile --windowed --name "${{ matrix.name }}" "main.py"
        elif [ "${{ runner.os }}" == "macOS" ]; then
          export MACOSX_DEPLOYMENT_TARGET=11.0
          uv run pyinstaller --noconfirm --onedir --windowed --name "${{ matrix.name }}" "main.py"
        fi

    # Step 6: Upload the built executable as a separate artifact for each build.
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: |
          dist/${{ matrix.name }}.exe
          dist/${{ matrix.name }}.app
        if-no-files-found: ignore # Prevents errors if one path doesn't exist